language: ruby
rvm:
  - 2.0.0
script:
  - cd pdf_renderer/1_prawn
  - bundle install
  - cd test/dummy
  - mkdir -p db
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
  - cd ../../mail_form
  - bundle install
  - cd test/dummy
  - mkdir -p db
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
  - cd ../templater
  - bundle install
  - bundle exec rake
  - cd ../handlers
  - bundle install
  - cd test/dummy
  - mkdir -p db
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
  - cd ../live_assets
  - bundle install
  - cd test/dummy
  - mkdir -p db
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../..
  - bundle exec rake
