language: ruby

services:
  - mongodb

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-1.7.8
  - rbx-2.2.1

before_install:
- travis_retry gem update --system
- travis_retry gem install bundler --pre
- gem --version
- bundle --version

script:
- travis_retry ruby script/ci/build.rb
