source "https://rubygems.org"

# Declare your gem's dependencies in handlers.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

platform :ruby do
  gem 'sqlite3'
end

platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end

platform :rbx do
  gem 'rdoc'
  gem 'racc'
  gem 'rubysl' # this requires all stdlib on Rubinius
end

gem 'pry'
gem 'pry-doc'
